### ISSUE TITLE
AUR support

### ISSUE THREAD

**Issue by evert-mouw** [eworm-de/pacredir#4]
Thanks for creating pacredir! I'm a new user and I'm wondering if compiles AUR packages in the cache are also redirected. It would shorten compilation time for a few of my older machines. Maybe the functionality is already in place but it is not explicitly mentioned in the README.md

**Comment by eworm-de** [comment]
Just some package files in the cache do not help, `pacman` needs to know about them. So at least a database file needs to be available. Have a look at how to create custom repositories:
https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Custom_local_repository
(Possibly there is better documentation, that is first one I could find.)

Then add a new repository for all your machines in `/etc/pacman.conf`:
```
[customrepo]
Include = /etc/pacman.d/pacredir
```

Not sure what happens if no "usual" server is configured...

But now that you have all the packages and a database file in one location just make it available via http in your network...

**Comment by eworm-de** [comment]
Oh, I closed too early. Feel free to comment and share your experience anyway!

**Comment by evert-mouw** [comment]
Thanks for your clarification!  I'll give it some thought. You can close this issue, as it indeed is out of scope for pacredir.
